# Basic Mapnik style settings. Values are explained here:
# https://github.com/mapnik/mapnik/wiki/XMLConfigReference

# Use '#ffffff' for a solid white background.
# Add two zeros to a six digit hex color code
# for a png (does not work with jpeg) image
# with a transparent background.
background_color: '#ffffff00' 

# Polygon feature settings
polygon_fill_color: '#fffff0'

# Line feature settings
line_stroke_color: '#483d8b'
line_stroke_width: '0.3'

# Point feature settings
marker_fill: '#0000ff'
marker_width: '5'
marker_height: '5'
marker_stroke_color: '#483d8b'
marker_stroke_width: '0.2'
marker_placement: 'point'
marker_allow_overlap-overlap: 'true'
