# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  # GeoConcerns behavior to FileSet.
  include ::GeoConcerns::GeoFileSetBehavior

end
